services:
  dockflow:
    build: .
    container_name: dockflow_app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/db:/app/backend/db
    restart: unless-stopped
